#!/usr/bin/perl
use strict;
use warnings;

# This program calculates the Fibonacci sequence up to a given number of terms.
# The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones.
# The sequence starts with 0 and 1, and the next numbers are generated by adding the two previous numbers.
# This program will prompt the user for the number of terms and then print the Fibonacci sequence up to that term.

# Function to calculate the Fibonacci sequence
sub fibonacci {
    my ($n) = @_;
    my @sequence = (0, 1);

    # Generate the Fibonacci sequence up to the nth term
    for (my $i = 2; $i < $n; $i++) {
        $sequence[$i] = $sequence[$i - 1] + $sequence[$i - 2];
    }

    return @sequence;
}

# Main program
print "Enter the number of terms for the Fibonacci sequence: ";
my $num_terms = <STDIN>;
chomp($num_terms);

# Validate the input to ensure it is a positive integer
if ($num_terms !~ /^\d+$/ || $num_terms <= 0) {
    die "Please enter a valid positive integer.\n";
}

# Open a file to write the Fibonacci sequence
open(my $fh, '>', 'fibonacci_sequence.txt') or die "Could not open file 'fibonacci_sequence.txt' $!";

# Calculate the Fibonacci sequence
my @fib_sequence = fibonacci($num_terms);

# Write the Fibonacci sequence to the file
foreach my $term (@fib_sequence) {
    print $fh "$term\n";
}

# Close the file handle
