-- Database: mega_ticket

-- Table: event
CREATE TABLE event (
    event_id serial,
    event_name TEXT,
    event_description TEXT,
    event_date DATE,
    event_venue TEXT,
    event_capacity INTEGER,
    event_price DECIMAL(10, 2),
    event_image_url TEXT,
    event_category TEXT,
    event_rating DECIMAL(3, 2),
    event_popularity INTEGER,
    event_age_restriction INTEGER,
    event_duration INTEGER,
    event_ticket_url TEXT,
    event_discount_code TEXT,
    event_is_sold_out BOOLEAN DEFAULT FALSE,
    event_location_latitude DECIMAL(10, 8),
    event_location_longitude DECIMAL(10, 8),
    event_category_id INTEGER,
    event_city TEXT,
    event_state TEXT,
    event_country TEXT,
    event_zip_code TEXT,
    event_timezone TEXT,
    event_is_outdoor BOOLEAN DEFAULT FALSE,
    event_is_indoor BOOLEAN DEFAULT FALSE,
    event_is_virtual BOOLEAN DEFAULT FALSE,
    event_age_restriction_min INTEGER,
    event_age_restriction_max INTEGER,
    event_is_family_friendly BOOLEAN DEFAULT FALSE,
    event_is_accessible BOOLEAN DEFAULT FALSE,
    event_is_pet_friendly BOOLEAN DEFAULT FALSE,
    event_alcohol_allowed BOOLEAN DEFAULT FALSE,
    event_food_allowed BOOLEAN DEFAULT FALSE,
    event_host_name TEXT,
    event_host_email TEXT,
    event_host_phone TEXT,
    event_host_address TEXT,
    event_host_city TEXT,
    event_host_state TEXT,
    event_host_country TEXT,
    event_host_zip_code TEXT,
    event_host_phone_number TEXT,
    event_host_website TEXT,
    event_host_social_media_links TEXT,
    event_terms_and_conditions TEXT,
    event_faq TEXT,
    event_refund_policy TEXT,
    event_payment_methods TEXT,
    event_is_member_only BOOLEAN DEFAULT FALSE,
    event_is_premium BOOLEAN DEFAULT FALSE,
    event_is_vip BOOLEAN DEFAULT FALSE,
    event_is_sponsored BOOLEAN DEFAULT FALSE,
    event_is_interactive BOOLEAN DEFAULT FALSE,
    event_is_live_streamed BOOLEAN DEFAULT FALSE,
    event_is_recorded BOOLEAN DEFAULT FALSE,
    event_video_url TEXT,
    event_audio_url TEXT,
    event_image_url_2 TEXT,
    event_image_url_3 TEXT,
    event_is_podcast BOOLEAN DEFAULT FALSE,
    event_is_sponsored_content BOOLEAN DEFAULT FALSE,
    event_is_family_friendly_2 BOOLEAN DEFAULT FALSE,
    event_is_safe BOOLEAN DEFAULT FALSE,
    event_is_verified BOOLEAN DEFAULT FALSE,
    event_is_trusted BOOLEAN DEFAULT FALSE,
    event_is_popular BOOLEAN DEFAULT FALSE,
    event_is_trending BOOLEAN DEFAULT FALSE,
    event_is_viral BOOLEAN DEFAULT FALSE,
    event_is_celebrity BOOLEAN DEFAULT FALSE,
    event_is_unique BOOLEAN DEFAULT FALSE,
    event_is_exclusive BOOLEAN DEFAULT FALSE,
    event_is_limited BOOLEAN DEFAULT FALSE,
    event_is_recommended BOOLEAN DEFAULT FALSE,
    event_is_reviewed BOOLEAN DEFAULT FALSE,
    event_is_rated BOOLEAN DEFAULT FALSE,
    event_is_commented BOOLEAN DEFAULT FALSE,
    event_is_liked BOOLEAN DEFAULT FALSE,
    event_is_shared BOOLEAN DEFAULT FALSE,
    event_is_saved BOOLEAN DEFAULT FALSE,
    event_is_followed BOOLEAN DEFAULT FALSE,
    event_is_subscribed BOOLEAN DEFAULT FALSE,
    event_is_invitation_only BOOLEAN DEFAULT FALSE,
    event_is_private BOOLEAN DEFAULT FALSE,
    event_is_collaborative BOOLEAN DEFAULT FALSE,
    event_is_community BOOLEAN DEFAULT FALSE,
    event_is_network BOOLEAN DEFAULT FALSE,
    event_is_gathering BOOLEAN DEFAULT FALSE,
    event_is_event BOOLEAN DEFAULT FALSE,
    event_is_occurrence BOOLEAN DEFAULT FALSE,
    event_is_activity BOOLEAN DEFAULT FALSE,
    event_is_function BOOLEAN DEFAULT FALSE,
    event_is_program BOOLEAN DEFAULT FALSE,
    event_is_game BOOLEAN DEFAULT FALSE,
    event_is_challenge BOOLEAN DEFAULT FALSE,
    event_is_competition BOOLEAN DEFAULT FALSE,
    event_is_tournament BOOLEAN DEFAULT FALSE,
    event_is_series BOOLEAN DEFAULT FALSE,
    event_is_series_2 BOOLEAN DEFAULT FALSE,
    event_is_episode BOOLEAN DEFAULT FALSE,
    event_is_chapter BOOLEAN DEFAULT FALSE,
    event_is_section BOOLEAN DEFAULT FALSE,
    event_is_segment BOOLEAN DEFAULT FALSE,
    event_is_part BOOLEAN DEFAULT FALSE,
    event_is_installment BOOLEAN DEFAULT FALSE,
    event_is_installment_2 BOOLEAN DEFAULT FALSE,
    event_is_installment_3 BOOLEAN DEFAULT FALSE,
    event_is_installment_4 BOOLEAN DEFAULT FALSE,
    event_is_installment_5 BOOLEAN DEFAULT FALSE,
    event_is_installment_6 BOOLEAN DEFAULT FALSE,
    event_is_installment_7 BOOLEAN DEFAULT FALSE,
    event_is_installment_8 BOOLEAN DEFAULT FALSE,
    event_is_installment_9 BOOLEAN DEFAULT FALSE,
    event_is_installment_10 BOOLEAN DEFAULT FALSE,
    event_is_installment_11 BOOLEAN DEFAULT FALSE,
    event_is_installment_12 BOOLEAN DEFAULT FALSE,
    event_is_installment_13 BOOLEAN DEFAULT FALSE,
    event_is_installment_14 BOOLEAN DEFAULT FALSE,
    event_is_installment_15 BOOLEAN DEFAULT FALSE,
    event_is_installment_16 BOOLEAN DEFAULT FALSE,
    event_is_installment_17 BOOLEAN DEFAULT FALSE,
    event_is_installment_18 BOOLEAN DEFAULT FALSE,
    event_is_installment_19 BOOLEAN DEFAULT FALSE,
    event_is_installment_20 BOOLEAN DEFAULT FALSE,
    event_is_installment_21 BOOLEAN DEFAULT FALSE,
    event_is_installment_22 BOOLEAN DEFAULT FALSE,
    event_is_installment_23 BOOLEAN DEFAULT FALSE,
    event_is_installment_24 BOOLEAN DEFAULT FALSE,
    event_is_installment_25 BOOLEAN DEFAULT FALSE,
    event_is_installment_26 BOOLEAN DEFAULT FALSE,
    event_is_installment_27 BOOLEAN DEFAULT FALSE,
    event_is_installment_28 BOOLEAN DEFAULT FALSE,
    event_is_installment_29 BOOLEAN DEFAULT FALSE,
    event_is_installment_30 BOOLEAN DEFAULT FALSE,
    event_is_installment_31 BOOLEAN DEFAULT FALSE,
    event_is_installment_32 BOOLEAN DEFAULT FALSE,
    event_is_installment_33 BOOLEAN DEFAULT FALSE,
    event_is_installment_34 BOOLEAN DEFAULT FALSE,
    event_is_installment_35 BOOLEAN DEFAULT FALSE,
    event_is_installment_36 BOOLEAN DEFAULT FALSE,
    event_is_installment_37 BOOLEAN DEFAULT FALSE,
    event_is_installment_38 BOOLEAN DEFAULT FALSE,
    event_is_installment_39 BOOLEAN DEFAULT FALSE,
    event_is_installment_40 BOOLEAN DEFAULT FALSE,
    event_is_installment_41 BOOLEAN DEFAULT FALSE,
    event_is_installment_42 BOOLEAN DEFAULT FALSE,
    event_is_installment_43 BOOLEAN DEFAULT FALSE,
    event_is_installment_44 BOOLEAN DEFAULT FALSE,
    event_is_installment_45 BOOLEAN DEFAULT FALSE,
    event_is_installment_46 BOOLEAN DEFAULT FALSE,
    event_is_installment_47 BOOLEAN DEFAULT FALSE,
    event_is_installment_48 BOOLEAN DEFAULT FALSE,
    event_is_installment_49 BOOLEAN DEFAULT FALSE,
    event_is_installment_50 BOOLEAN DEFAULT FALSE,
    event_is_installment_51 BOOLEAN DEFAULT FALSE,
    event_is_installment_52 BOOLEAN DEFAULT FALSE,
    event_is_installment_53 BOOLEAN DEFAULT FALSE,
    event_is_installment_54 BOOLEAN DEFAULT FALSE,
    event_is_installment_55 BOOLEAN DEFAULT FALSE,
    event_is_installment_56 BOOLEAN DEFAULT FALSE,
    event_is_installment_57 BOOLEAN DEFAULT FALSE,
    event_is_installment_58 BOOLEAN DEFAULT FALSE,
    event_is_installment_59 BOOLEAN DEFAULT FALSE,
    event_is_installment_60 BOOLEAN DEFAULT FALSE,
    event_is_installment_61 BOOLEAN DEFAULT FALSE,
    event_is_installment_62 BOOLEAN DEFAULT FALSE,
    event_is_installment_63 BOOLEAN DEFAULT FALSE,
    event_is_installment_64 BOOLEAN DEFAULT FALSE,
    event_is_installment_65 BOOLEAN DEFAULT FALSE,
    event_is_installment_66 BOOLEAN DEFAULT FALSE,
    event_is_installment_67 BOOLEAN DEFAULT FALSE,
    event_is_installment_68 BOOLEAN DEFAULT FALSE,
    event_is_installment_69 BOOLEAN DEFAULT FALSE,
    event_is_installment_70 BOOLEAN DEFAULT FALSE,
    event_is_installment_71 BOOLEAN DEFAULT FALSE,
    event_is_installment_72 BOOLEAN DEFAULT FALSE,
    event_is_installment_73 BOOLEAN DEFAULT FALSE,
    event_is_installment_74 BOOLEAN DEFAULT FALSE,
    event_is_installment_75 BOOLEAN DEFAULT FALSE,
    event_is_installment_76 BOOLEAN DEFAULT FALSE,
    event_is_installment_77 BOOLEAN DEFAULT FALSE,
    event_is_installment_78 BOOLEAN DEFAULT FALSE,
    event_is_installment_79 BOOLEAN DEFAULT FALSE,
    event_is_installment_80 BOOLEAN DEFAULT FALSE,
    event_is_installment_81 BOOLEAN DEFAULT FALSE,
    event_is_installment_82 BOOLEAN DEFAULT FALSE,
    event_is_installment_83 BOOLEAN DEFAULT FALSE,
    event_is_installment_84 BOOLEAN DEFAULT FALSE,
    event_is_installment_85 BOOLEAN DEFAULT FALSE,
    event_is_installment_86 BOOLEAN DEFAULT FALSE,
    event_is_installment_87 BOOLEAN DEFAULT FALSE,
    event_is_installment_88 BOOLEAN DEFAULT FALSE,
    event_is_installment_89 BOOLEAN DEFAULT FALSE,
    event_is_installment_90 BOOLEAN DEFAULT FALSE,
    event_is_installment_91 BOOLEAN DEFAULT FALSE,
    event_is_installment_92 BOOLEAN DEFAULT FALSE,
    event_is_installment_93 BOOLEAN DEFAULT FALSE,
    event_is_installment_94 BOOLEAN DEFAULT FALSE,
    event_is_installment_95 BOOLEAN DEFAULT FALSE,
    event_is_installment_96 BOOLEAN DEFAULT FALSE,
    event_is_installment_97 BOOLEAN DEFAULT FALSE,
    event_is_installment_98 BOOLEAN DEFAULT FALSE,
    event_is_installment_99 BOOLEAN DEFAULT FALSE,
    event_is_installment_100 BOOLEAN DEFAULT FALSE,
    event_is_installment_101 BOOLEAN DEFAULT FALSE,
    event_is_installment_102 BOOLEAN DEFAULT FALSE,
    event_is_installment_103 BOOLEAN DEFAULT FALSE,
    event_is_installment_104 BOOLEAN DEFAULT FALSE,
    event_is_installment_105 BOOLEAN DEFAULT FALSE,
    event_is_installment_106 BOOLEAN DEFAULT FALSE,
    event_is_installment_107 BOOLEAN DEFAULT FALSE,
    event_is_installment_108 BOOLEAN DEFAULT FALSE,
    event_is_installment_109 BOOLEAN DEFAULT FALSE,
    event_is_installment_110 BOOLEAN DEFAULT FALSE,
    event_is_installment_111 BOOLEAN DEFAULT FALSE,
    event_is_installment_112 BOOLEAN DEFAULT FALSE,
    event_is_installment_113 BOOLEAN DEFAULT FALSE,
    event_is_installment_114 BOOLEAN DEFAULT FALSE,
    event_is_installment_115 BOOLEAN DEFAULT FALSE,
    event_is_installment_116 BOOLEAN DEFAULT FALSE,
    event_is_installment_117 BOOLEAN DEFAULT FALSE,
    event_is_installment_118 BOOLEAN DEFAULT FALSE,
    event_is_installment_119 BOOLEAN DEFAULT FALSE,
    event_is_installment_120 BOOLEAN DEFAULT FALSE,
    event_is_installment_121 BOOLEAN DEFAULT FALSE,
    event_is_installment_122 BOOLEAN DEFAULT FALSE,
    event_is_installment_123 BOOLEAN DEFAULT FALSE,
    event_is_installment_124 BOOLEAN DEFAULT FALSE,
    event_is_installment_125 BOOLEAN DEFAULT FALSE,
    event_is_installment_126 BOOLEAN DEFAULT FALSE,
    event_is_installment_127 BOOLEAN DEFAULT FALSE,
    event_is_installment_128 BOOLEAN DEFAULT FALSE,
    event_is_installment_129 BOOLEAN DEFAULT FALSE,
    event_is_installment_130 BOOLEAN DEFAULT FALSE,
    event_is_installment_131 BOOLEAN DEFAULT FALSE,
    event_is_installment_132 BOOLEAN DEFAULT FALSE,
    event_is_installment_133 BOOLEAN DEFAULT FALSE,
    event_is_installment_134 BOOLEAN DEFAULT FALSE,
    event_is_installment_135 BOOLEAN DEFAULT FALSE,
    event_is_installment_136 BOOLEAN DEFAULT FALSE,
    event_is_installment_137 BOOLEAN DEFAULT FALSE,
    event_is_installment_138 BOOLEAN DEFAULT FALSE,
    event_is_installment_139 BOOLEAN DEFAULT FALSE,
    event_is_installment_140 BOOLEAN DEFAULT FALSE,
    event_is_installment_141 BOOLEAN DEFAULT FALSE,
    event_is_installment_142 BOOLEAN DEFAULT FALSE,
    event_is_installment_143 BOOLEAN DEFAULT FALSE,
    event_is_installment_144 BOOLEAN DEFAULT FALSE,
    event_is_installment_145 BOOLEAN DEFAULT FALSE,
    event_is_installment_146 BOOLEAN DEFAULT FALSE,
    event_is_installment_147 BOOLEAN DEFAULT FALSE,
    event_is_installment_148 BOOLEAN DEFAULT FALSE,
    event_is_installment_149 BOOLEAN DEFAULT FALSE,
    event_is_installment_150 BOOLEAN DEFAULT FALSE,
    event_is_installment_151 BOOLEAN DEFAULT FALSE,
    event_is_installment_152 BOOLEAN DEFAULT FALSE,
    event_is_installment_153 BOOLEAN DEFAULT FALSE,
    event_is_installment_154 BOOLEAN DEFAULT FALSE,
    event_is_installment_155 BOOLEAN DEFAULT FALSE,
    event_is_installment_156 BOOLEAN DEFAULT FALSE,
    event_is_installment_157 BOOLEAN DEFAULT FALSE,
    event_is_installment_158 BOOLEAN DEFAULT FALSE,
    event_is_installment_159 BOOLEAN DEFAULT FALSE,
    event_is_installment_160 BOOLEAN DEFAULT FALSE,
    event_is_installment_161 BOOLEAN DEFAULT FALSE,
    event_is_installment_162 BOOLEAN DEFAULT FALSE,
    event_is_installment_163 BOOLEAN DEFAULT FALSE,
    event_is_installment_164 BOOLEAN DEFAULT FALSE,
    event_is_installment_165 BOOLEAN DEFAULT FALSE,
    event_is_installment_166 BOOLEAN DEFAULT FALSE,
    event_is_installment_167 BOOLEAN DEFAULT FALSE,
    event_is_installment_168 BOOLEAN DEFAULT FALSE,
    event_is_installment_169 BOOLEAN DEFAULT FALSE,
    event_is_installment_170 BOOLEAN DEFAULT FALSE,
    event_is_installment_171 BOOLEAN DEFAULT FALSE,
    event_is_installment_172 BOOLEAN DEFAULT FALSE,
    event_is_installment_173 BOOLEAN DEFAULT FALSE,
    event_is_installment_174 BOOLEAN DEFAULT FALSE,
    event_is_installment_175 BOOLEAN DEFAULT FALSE,
    event_is_installment_176 BOOLEAN DEFAULT FALSE,
    event_is_installment_177 BOOLEAN DEFAULT FALSE,
    event_is_installment_178 BOOLEAN DEFAULT FALSE,
    event_is_installment_179 BOOLEAN DEFAULT FALSE,
    event_is_installment_180 BOOLEAN DEFAULT FALSE,
    event_is_installment_181 BOOLEAN DEFAULT FALSE,
    event_is_installment_182 BOOLEAN DEFAULT FALSE,
    event_is_installment_183 BOOLEAN DEFAULT FALSE,
    event_is_installment_184 BOOLEAN DEFAULT FALSE,
    event_is_installment_185 BOOLEAN DEFAULT FALSE,
    event_is_installment_186 BOOLEAN DEFAULT FALSE,
    event_is_installment_187 BOOLEAN DEFAULT FALSE,
    event_is_installment_188 BOOLEAN DEFAULT FALSE,
    event_is_installment_189 BOOLEAN DEFAULT FALSE,
    event_is_installment_190 BOOLEAN DEFAULT FALSE,
    event_is_installment_191 BOOLEAN DEFAULT FALSE,
    event_is_installment_192 BOOLEAN DEFAULT FALSE,
    event_is_installment_193 BOOLEAN DEFAULT FALSE,
    event_is_installment_194 BOOLEAN DEFAULT FALSE,
    event_is_installment_195 BOOLEAN DEFAULT FALSE,
    event_is_installment_196 BOOLEAN DEFAULT FALSE,
    event_is_installment_197 BOOLEAN DEFAULT FALSE,
    event_is_installment_198 BOOLEAN DEFAULT FALSE,
    event_is_installment_199 BOOLEAN DEFAULT FALSE,
    event_is_installment_200 BOOLEAN DEFAULT FALSE,
    event_is_installment_201 BOOLEAN DEFAULT FALSE,
    event_is_installment_202 BOOLEAN DEFAULT FALSE,
    event_is_installment_203 BOOLEAN DEFAULT FALSE,
    event_is_installment_204 BOOLEAN DEFAULT FALSE,
    event_is_installment_205 BOOLEAN DEFAULT FALSE,
    event_is_installment_206 BOOLEAN DEFAULT FALSE,
    event_is_installment_207 BOOLEAN DEFAULT FALSE,
    event_is_installment_208 BOOLEAN DEFAULT FALSE,
    event_is_installment_209 BOOLEAN DEFAULT FALSE,
    event_is_installment_210 BOOLEAN DEFAULT FALSE,
    event_is_installment_211 BOOLEAN DEFAULT FALSE,
    event_is_installment_212 BOOLEAN DEFAULT FALSE,
    event_is_installment_213 BOOLEAN DEFAULT FALSE,
    event_is_installment_214 BOOLEAN DEFAULT FALSE,
    event_is_installment_215 BOOLEAN DEFAULT FALSE,
    event_is_installment_216 BOOLEAN DEFAULT FALSE,
    event_is_installment_217 BOOLEAN DEFAULT FALSE,
    event_is_installment_218 BOOLEAN DEFAULT FALSE,
    event_is_installment_219 BOOLEAN DEFAULT FALSE,
    event_is_installment_220 BOOLEAN DEFAULT FALSE,
    event_is_installment_221 BOOLEAN DEFAULT FALSE,
    event_is_installment_222 BOOLEAN DEFAULT FALSE,
    event_is_installment_223 BOOLEAN DEFAULT FALSE,
    event_is_installment_224 BOOLEAN DEFAULT FALSE,
    event_is_installment_225 BOOLEAN DEFAULT FALSE,
    event_is_installment_226 BOOLEAN DEFAULT FALSE,
    event_is_installment_227 BOOLEAN DEFAULT FALSE,
    event_is_installment_228 BOOLEAN DEFAULT FALSE,
    event_is_installment_229 BOOLEAN DEFAULT FALSE,
    event_is_installment_230 BOOLEAN DEFAULT FALSE,
    event_is_installment_231 BOOLEAN DEFAULT FALSE,
    event_is_installment_232 BOOLEAN DEFAULT FALSE,
    event_is_installment_233 BOOLEAN DEFAULT FALSE,
    event_is_installment_234 BOOLEAN DEFAULT FALSE,
    event_is_installment_235 BOOLEAN DEFAULT FALSE,
    event_is_installment_236 BOOLEAN DEFAULT FALSE,
    event_is_installment_237 BOOLEAN DEFAULT FALSE,
    event_is_installment_238 BOOLEAN DEFAULT FALSE,
    event_is_installment_239 BOOLEAN DEFAULT FALSE,
    event_is_installment_240 BOOLEAN DEFAULT FALSE,
    event_is_installment_241 BOOLEAN DEFAULT FALSE,
    event_is_installment_242 BOOLEAN DEFAULT FALSE,
    event_is_installment_243 BOOLEAN DEFAULT FALSE,
    event_is_installment_244 BOOLEAN DEFAULT FALSE,
    event_is_installment_245 BOOLEAN DEFAULT FALSE,
    event_is_installment_246 BOOLEAN DEFAULT FALSE,
    event_is_installment_247 BOOLEAN DEFAULT FALSE,
    event_is_installment_248 BOOLEAN DEFAULT FALSE,
    event_is_installment_249 BOOLEAN DEFAULT FALSE,
    event_is_installment_250 BOOLEAN DEFAULT FALSE,
    event_is_installment_251 BOOLEAN DEFAULT FALSE,
    event_is_installment_252 BOOLEAN DEFAULT FALSE,
    event_is_installment_253 BOOLEAN DEFAULT FALSE,
    event_is_installment_254 BOOLEAN DEFAULT FALSE,
    event_is_installment_255 BOOLEAN DEFAULT FALSE
]